on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: [earthly-satellite#gha-earthly-intellij-plugin]
    env:
      FORCE_COLOR: 1
      EARTHLY_CONVERSION_PARALLELISM: "5"
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      EARTHLY_INSTALL_ID: "earthly-lib-githubactions"
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Release
        run: earthly --push +publish --version=$RELEASE_VERSION
