on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  job-1:
    runs-on: [earthly-satellite#intellij-plugin3, earthly-cache-folder#/root/cache]
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
      #      - uses: earthly/actions/setup-earthly@v1
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Release
        run: |-
          env ; earthly --verbose +install