on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  job-1:
    runs-on: [earthly-satellite#nacho-3, earthly-cache-folder#/root/.m2]
    env:
      FORCE_COLOR: 1
      EARTHLY_CONVERSION_PARALLELISM: "5"
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      EARTHLY_INSTALL_ID: "earthly-lib-githubactions"
    steps:
      - uses: actions/checkout@v2
      #      - uses: earthly/actions/setup-earthly@v1
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Release
        run: |-
          ls / && \
          env
        
